[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
rpassword = "7.3"
common = { path = "../common" }
csv = "1.4.0"
chrono = { version = "0.4", features = ["serde"] }
ratatui = {version = "0.30"}
crossterm = { version = "0.29", features = ["event-stream"]}
futures = "0.3.34"

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }
server = { path = "../server" }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "chrono"] }
